### PR TITLE
HealthKit Step count

### PR DESCRIPTION
**Pull request by jijopulikkottil**

### CODE REVIEW

**Comment by avaidyam** [comment]
@jijopulikkottil I've merged this but please ensure it works correctly with the new LAMP-swift repository changes.

**Comment by jijopulikkottil** [comment]
> @jijopulikkottil I've merged this but please ensure it works correctly with the new LAMP-swift repository changes.

Noticed it after made PR, I can make it work and give a PR again.

**Comment by avaidyam** [comment]
@jijopulikkottil Please don't tag the repository yourself - the CI/CD should push all master builds to TestFlight and all tagged builds to production (live for all users) so if you tag them yourself, it circumvents our ability to test each release before we submit it.

**Comment by jijopulikkottil** [comment]
Sorry, I done that without thinking to test the latest LAMP-Swift repository, In Xcode, we have to enter tag value for swift package to get the latest. I will try other way in future.

**Comment by jijopulikkottil** [comment]
The current LAMP-Swift have compilation errors, So more tasks and I couldn't provide a PR immediately.. hope its fine.

**Comment by avaidyam** [comment]
@jijopulikkottil No problem - please PR the `LAMP-swift` repository when you have fixed them.

**Pull request merged**
